name: Update README with Recent Activity

on:
  schedule:
    # This makes the action run automatically every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # This allows you to run the action manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update-Readme-with-Activity
    
    # This gives the action permission to write to your repository
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
